import {createHashRouter,storyHref,viewHref} from './story-routes.js';
import {browserAnalytics} from './analytics.js';
import {promptMarkup,choiceCard} from './choice-ui.js';
import audioManifest from './audio-manifest.js';
import {StoryAudio,currentClip,revealedClip,supportsStoryAudio} from './story-audio.js';
import {stories,storyById} from './stories.js';
import {beginStory,answerStory,advanceStory} from './story-engine.js';
import {roadmap,storyScreen,storyFinish,storyUiText,bookIcon,speakerIcon,stopIcon} from './story-ui.js';
import {defaultStoryLangs,normalizeStoryLangs,routeStoryLangs,textFor} from './story-languages.js';
import {units,lessons,words,allQuestions} from './course.js';
import {KEY,initial,restore,start,current,answer,advance,streak,orderedChoices} from './engine.js';
const root=document.querySelector('#app');
let storageWorks=true,state;try{state=restore(localStorage.getItem(KEY));}catch{state=initial();storageWorks=false;}
const analytics=browserAnalytics(state);
let view='stories',selected=null,result=null,exitPrompt=false,activeStory=null,storyResult=null;
let storyLangs={...defaultStoryLangs};try{storyLangs=normalizeStoryLangs(JSON.parse(localStorage.getItem('duo34-story-langs'))||defaultStoryLangs);}catch{}
let soundEnabled=true;try{soundEnabled=localStorage.getItem('duo34-sound')!=='off';}catch{}
const storyAudio=new StoryAudio({audio:new Audio(),enabled:soundEnabled,onChange:updateAudioControls,persist:enabled=>localStorage.setItem('duo34-sound',enabled?'on':'off')});
function updateAudioControls(){
 const ui=storyUiText(storyLangs.ui),toggle=root.querySelector('[data-action="story-sound"]'),audioStatus=root.querySelector('#audio-status');
 if(toggle){toggle.textContent=storyAudio.enabled?ui.autoOn:ui.autoOff;toggle.setAttribute('aria-pressed',String(storyAudio.enabled));}
 for(const button of root.querySelectorAll('[data-action="story-line-audio"]')){
  const active=button.dataset.clipKey===storyAudio.clip?.key;
  const busy=active&&['loading','playing'].includes(storyAudio.status);
  const loading=active&&storyAudio.status==='loading';
  const failed=active&&['error','blocked','missing'].includes(storyAudio.status);
  const narrator=button.dataset.narrator==='true';
  const label=busy?(narrator?ui.stopNarrator:ui.stopLine):failed?ui.retry:narrator?ui.listenNarrator:ui.listenLine;
  button.innerHTML=busy?stopIcon:speakerIcon;
  button.classList.toggle('is-playing',busy);
  button.classList.toggle('is-loading',loading);
  button.classList.toggle('has-error',failed);
  button.setAttribute('aria-label',label);button.title=loading?ui.loadingTitle:label;
 }
 if(audioStatus)audioStatus.textContent=({loading:ui.loading,playing:storyAudio.clip?.who==='narrator'?ui.narratorSpeaking:ui.characterSpeaking,blocked:ui.blocked,missing:ui.missing,error:ui.audioError}[storyAudio.status]||'');
}
window.addEventListener('pagehide',()=>storyAudio.leave());
document.addEventListener('visibilitychange',()=>{if(document.hidden){storyAudio.stop();storyAudio.notify();}});

const teachers={owl:{name:'Сова',role:'Флирт и намёки',color:'#c7b6ff',letter:'С',quote:'Слова взрослые. Объяснения человеческие.',good:'Именно. Ты всё правильно понял.',bad:'Тут есть нюанс. Разберёмся.'},fak:{name:'Дядя Фак',role:'Кафедра крепких выражений',color:'#b7ee65',letter:'Ф',quote:'Знать ругательство и вовремя промолчать — два разных навыка.',good:'Зачёт. Галстук можно не надевать.',bad:'Почти. Но смысл свернул не туда.'},krinzh:{name:'Кринжина',role:'Практикум неловкости',color:'#ffbb8a',letter:'К',quote:'Я уже сказала это на свидании. Учись на моей ошибке.',good:'Ура! Одной неловкой ситуацией меньше.',bad:'Знакомая ошибка. Я тоже так думала.'}};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageWorks=false;}}
function saveStoryLangs(){storyLangs=normalizeStoryLangs(storyLangs);try{localStorage.setItem('duo34-story-langs',JSON.stringify(storyLangs));}catch{}}
function avatar(id='owl',size='',mood=''){const t=teachers[id];return `<svg class="avatar ${size} ${mood}" viewBox="0 0 100 105" role="img" aria-label="${t.name}"><g fill="${t.color}"><rect x="13" y="12" width="74" height="78" rx="${id==='fak'?18:34}"/>${id==='owl'?'<path d="M16 35L15 4L38 19M84 35L85 4L62 19"/>':''}</g>${id==='fak'?'<path d="M25 17L47 6L70 17" fill="#526537"/><path d="M45 84H56L61 100H41Z" fill="#b7ee65"/>':id==='krinzh'?'<path d="M14 39Q5 5 40 9Q76 0 88 31L59 18L49 32L34 22Z" fill="#9a5640"/>':''}<g class="eyes" fill="#20242c"><rect x="29" y="41" width="10" height="15" rx="5"/><rect x="61" y="41" width="10" height="15" rx="5"/></g>${mood==='wrong'?'<path d="M40 73Q50 63 60 73" stroke="#20242c" stroke-width="4" fill="none" stroke-linecap="round"/>':'<path d="M40 66Q50 78 60 66" stroke="#20242c" stroke-width="4" fill="none" stroke-linecap="round"/>'}</svg>`;}
function button(label,action,extra='',cls=''){return `<button class="btn ${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function brand(){return '<span class="brand">duo<span>34</span><sup class="age">18+</sup></span>';}
const shellCopy={
 en:{nav:'Main navigation',stories:'Stories',course:'Practice',words:'Dictionary',progress:'Progress',tagline:'Language without censorship.',season:'Season one',storyCount:'stories',top:'LANGUAGE / 18+ STORIES',streak:'Day streak'},
 ru:{nav:'Основная навигация',stories:'Истории',course:'Тренировка',words:'Словарь',progress:'Прогресс',tagline:'Язык. Без купюр.',season:'Первый сезон',storyCount:'историй',top:'ЯЗЫК / ИСТОРИИ 18+',streak:'Серия дней'},
 es:{nav:'Navegación principal',stories:'Historias',course:'Práctica',words:'Diccionario',progress:'Progreso',tagline:'Idioma sin censura.',season:'Primera temporada',storyCount:'historias',top:'IDIOMA / HISTORIAS 18+',streak:'Racha diaria'},
 zh:{nav:'主导航',stories:'故事',course:'练习',words:'词典',progress:'进度',tagline:'不删减的语言。',season:'第一季',storyCount:'个故事',top:'语言 / 18+ 故事',streak:'连续天数'},
 uk:{nav:'Основна навігація',stories:'Історії',course:'Тренування',words:'Словник',progress:'Прогрес',tagline:'Мова без цензури.',season:'Перший сезон',storyCount:'історій',top:'МОВА / ІСТОРІЇ 18+',streak:'Серія днів'},
 ja:{nav:'メインナビゲーション',stories:'ストーリー',course:'練習',words:'辞書',progress:'進捗',tagline:'遠慮なしの言葉。',season:'シーズン1',storyCount:'ストーリー',top:'言語 / 18+ ストーリー',streak:'連続日数'}
};
function shell(content,locale='ru'){const copy=shellCopy[locale]||shellCopy.en,count=Object.keys(state.storyCompleted).length;return `<div class="shell" lang="${locale}" data-language-role="ui"><aside class="sidebar">${brand()}<nav class="nav" aria-label="${copy.nav}">${[['stories',bookIcon,copy.stories],['course','↻',copy.course],['words','Aa',copy.words],['progress','▥',copy.progress]].map(([id,icon,label])=>`<button data-action="nav" data-view="${id}" class="${view===id||(id==='course'&&view==='review')?'active':''}" ${view===id?'aria-current="page"':''}><span class="symbol" aria-hidden="true">${icon}</span>${label}</button>`).join('')}</nav><div class="side-bottom"><b>${copy.tagline}</b>${copy.season} · ${count} / ${stories.length} ${copy.storyCount}<div class="meter" style="margin-top:14px"><i style="width:${count/stories.length*100}%"></i></div></div></aside><main class="workspace"><header class="topbar"><span class="mobile-brand">${brand()}</span><span class="meta">${copy.top}</span><div class="stats"><span class="fire" title="${copy.streak}">♨ ${streak(state)}</span><span class="xp">✦ ${state.xp} XP</span></div></header>${content}</main></div>`;}
function head(title,subtitle,teacher='owl'){return `<div class="course-head"><div><div class="eyebrow">Английский за пределами учебника</div><h1 tabindex="-1">${title}</h1><p class="subtitle">${subtitle}</p></div>${avatar(teacher)}</div>`;}
function course(){const next=lessons.find(l=>state.completed[l.id]===undefined);return shell(`${head('Тренировка слов.','Короткая практика между историями — когда захочется.')} ${state.session?`<div class="resume"><div><b>Ты остановился на середине</b><div class="meta">${state.session.mode==='review'?'Повторение ошибок':lessons.find(l=>l.id===state.session.lessonId)?.title} · задание ${state.session.index+1} из ${state.session.ids.length}</div></div>${button('Продолжить','resume')}</div>`:''}<div class="layout"><div>${units.map((u,i)=>`<section class="unit" style="--unit:${u.color}"><div class="unit-head"><div><small>РАЗДЕЛ ${i+1}</small><h2>${u.title}</h2><small>${u.subtitle}</small></div><span class="unit-no">0${i+1}</span></div>${lessons.filter(l=>l.unit===i).map((l,j)=>{const done=state.completed[l.id]!==undefined;return `<button class="lesson" data-action="start" data-id="${l.id}"><span class="lesson-icon ${done?'done':next?.id===l.id?'next':''}">${done?'✓':j+1}</span><span class="text"><h3>${l.title}</h3><small>${done?`Лучший результат: ${state.completed[l.id]} / 8`:'8 заданий · ~3 минуты'}</small></span><span class="chevron" aria-hidden="true">${done?'↻':'→'}</span></button>`;}).join('')}</section>`).join('')}</div><aside class="aside"><div class="card"><div class="teacher-row">${avatar('fak')}<div><b>Дядя Фак</b><div class="meta">Твой преподаватель</div></div></div><p class="quote">«${teachers.fak.quote}»</p></div><div class="card"><h3>Практика без пробелов</h3><p>${state.mistakes.length?`Заданий на повторение: ${state.mistakes.length}. Разберись с тем, что пока путается.`:'Ошибки из уроков попадут сюда. Повторяй их в своём темпе.'}</p>${button('Повторить ошибки','review','', 'secondary block')}</div><div class="card"><h3>Урок дня</h3><p>Один короткий урок — уже практика. Серия растёт за завершённые занятия.</p><div class="progress-label"><span>Сегодня</span><span>${didToday()?'Готово ✓':'Можно начать'}</span></div><div class="meter"><i style="width:${didToday()?100:0}%"></i></div></div></aside></div>`);}
function didToday(){const d=new Date(),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return state.days.includes(k);}
function teacherForSession(){const l=lessons.find(l=>l.id===state.session?.lessonId);return l?units[l.unit].teacher:'krinzh';}
function lesson(){const t=state.session,q=current(state);if(!t||!q){view='course';return course();}const teacher=teacherForSession(),who=teachers[teacher],correct=t.selected===q.correct,mood=t.answered?(correct?'correct':'wrong'):'';return `<main class="lesson-screen"><header class="lesson-top"><button class="close" data-action="exit" aria-label="Выйти из урока">×</button><div class="meter" role="progressbar" aria-label="Прогресс урока" aria-valuenow="${t.index+(t.answered?1:0)}" aria-valuemin="0" aria-valuemax="${t.ids.length}"><i style="width:${(t.index+(t.answered?1:0))/t.ids.length*100}%"></i></div><span class="meta">${t.index+1} / ${t.ids.length}</span></header>${exitPrompt?`<div class="exit-confirm" role="alert"><b>Прогресс этого урока сохранится.</b><p class="meta">Вернуться можно с главного экрана.</p>${button('К курсу','leave')}${button('Остаться','stay','','secondary')}</div>`:''}<section class="question"><div class="teacher-row">${avatar(teacher,'',mood)}<div><b>${who.name}</b><div class="meta">${q.type==='meaning'?'Разбираемся со смыслом':'Проверяем контекст'}</div></div></div>${promptMarkup(q.prompt,q.promptRu,`prompt-${q.id}`,'h1')}${q.phrase?`<div class="phrase" lang="en">${esc(q.phrase)}</div>`:''}<div class="answers" role="group" aria-label="Варианты ответа">${orderedChoices(q).map((c,i)=>choiceCard({id:`option-${q.id}-${i}`,en:q.choiceLabels[c].en,ru:q.choiceLabels[c].ru,index:i,action:'choose',attribute:'choice',value:i,answered:t.answered,selected:(t.answered?t.selected:selected)===c,good:t.answered&&c===q.correct,bad:t.answered&&c===t.selected&&!correct})).join('')}</div></section>${t.answered?`<div class="feedback ${correct?'':'bad'}" role="status"><h3>${correct?who.good:who.bad}</h3>${correct?'':`<p style="margin-bottom:9px"><b>Ответ: ${esc(q.correct)}</b></p>`}<p>${esc(q.explanation)}</p></div>`:''}<footer class="lesson-bottom"><span class="meta">${t.answered?'Смысл важнее буквального перевода.':'Выбери один ответ'}</span>${button(t.answered?(t.index===t.ids.length-1?'Завершить урок':'Дальше'):'Проверить',t.answered?'next':'check',!t.answered&&selected===null?'disabled':'')}</footer></main>`;}
function review(){return shell(`${head('Разберём ошибки.','То, что стоит попробовать ещё раз.','krinzh')}<div class="card"><h2>${state.mistakes.length?`Заданий на повторение: ${state.mistakes.length}`:'Пока всё чисто'}</h2><p>${state.mistakes.length?'Верный ответ убирает задание из повторения. Не торопись — объяснение всегда рядом.':'Здесь появятся задания, в которых ты ошибёшься. Можно начать новый урок или пройти любимый ещё раз.'}</p>${button(state.mistakes.length?'Начать повторение':'Перейти к курсу',state.mistakes.length?'start-review':'course','','block')}</div>${state.mistakes.length?`<div class="word-grid">${[...new Set(state.mistakes.map(id=>allQuestions.find(q=>q.id===id).wordId))].map(id=>{const w=words.find(w=>w.id===id);return `<div class="card"><h3 lang="en">${esc(w.phrase)}</h3><p>${esc(w.meaning)}</p></div>`;}).join('')}</div>`:''}`);}
function wordCards(query=''){const found=words.filter(w=>(w.phrase+' '+w.meaning+' '+w.register).toLocaleLowerCase().includes(query.toLocaleLowerCase()));return found.length?found.map(w=>`<article class="card"><h3 lang="en">${esc(w.phrase)}</h3><p class="meaning">${esc(w.meaning)}</p><span class="tag">${esc(w.register)}</span><p>${esc(w.explanation)}</p></article>`).join(''):'<p class="empty">Ничего не найдено. Попробуй другое слово.</p>';}
function dictionary(){return shell(`${head('Словарь без купюр.','36 выражений. Со смыслом и контекстом.')}<label class="sr" for="search">Найти слово или перевод</label><input id="search" class="search" type="search" placeholder="Слово, перевод или степень грубости…" autocomplete="off"><div class="word-grid" id="word-list">${wordCards()}</div><p class="sources">Для проверки значений: <a href="https://dictionary.cambridge.org/dictionary/english/" target="_blank" rel="noopener noreferrer">Cambridge Dictionary ↗</a><a href="https://www.merriam-webster.com/" target="_blank" rel="noopener noreferrer">Merriam-Webster ↗</a><br>Курс вводный. Оттенки зависят от региона, отношений и интонации.</p>`);}
function progress(){const n=Object.keys(state.completed).length,total=Object.values(state.completed).reduce((a,b)=>a+b,0);return shell(`${head('Это уже прогресс.','Истории прочитаны. Неловкость осознана.')}<div class="card"><h2>Истории · ${Object.keys(state.storyCompleted).length} / ${stories.length}</h2><p>Первый сезон. Каждую историю можно перечитать с дорожки.</p><div class="progress-label"><span>Прочитано</span><span>${Math.round(Object.keys(state.storyCompleted).length/stories.length*100)}%</span></div><div class="meter"><i style="width:${Math.round(Object.keys(state.storyCompleted).length/stories.length*100)}%"></i></div></div><div class="result-stats"><div class="card"><b>${n} / 9</b><small>уроков пройдено</small></div><div class="card"><b>${state.xp}</b><small>XP заработано</small></div><div class="card"><b>${streak(state)}</b><small>дней подряд</small></div></div><div class="card"><h2>Первый курс</h2><div class="progress-label"><span>Пройдено</span><span>${Math.round(n/9*100)}%</span></div><div class="meter"><i style="width:${n/9*100}%"></i></div><p>${n?`Лучшие результаты: ${total} правильных ответов из ${n*8} в завершённых уроках.`:'Первый урок займёт около трёх минут.'}</p>${button(n===9?'Пройти ещё раз':'Продолжить курс','course','','block')}</div><div class="card"><h3>Сохранено на этом устройстве</h3><p>Личное сохранение хранится в этом браузере. Для общей статистики на сервер передаются открытия приложения, начала и завершения занятий со случайным ID браузера, без имени и контактов. При очистке данных сайта он пропадёт; между устройствами пока не синхронизируется.</p><p>XP: 5 за верную реплику, 20 за первое завершение истории; в тренировке — 10 за первое завершение урока. Повторения тоже дают XP. Серия учитывает завершённые занятия по местной дате устройства.</p></div>`);}
function finish(){return `<main class="lesson-screen"><header class="lesson-top"><button class="close" data-action="course" aria-label="Вернуться к курсу">×</button><span class="meta">${result.mode==='review'?'ПОВТОРЕНИЕ ЗАВЕРШЕНО':'УРОК ЗАВЕРШЁН'}</span></header><section class="result">${avatar('owl','big','correct')}<h1 tabindex="-1">${result.score===result.total?'Без единой неловкости.':'Теперь понятнее.'}</h1><p>${result.score===result.total?'Все ответы верные. Можно двигаться дальше.':'Ошибки — часть практики. Их можно разобрать ещё раз.'}</p><div class="result-stats"><div class="card"><b>${result.score} / ${result.total}</b><small>верных ответов</small></div><div class="card"><b>+${result.xp}</b><small>XP за урок</small></div><div class="card"><b>${streak(state)}</b><small>дней подряд</small></div></div><div class="result-actions">${button('К курсу','course')}${state.mistakes.length?button('Повторить ошибки','review','','secondary'):''}</div></section></main>`;}
function intro(){return `<main class="intro"><div class="intro-inner">${brand()}<div>${avatar('owl','big')}</div><h1 tabindex="-1">У этих историй<br>нет цензора.</h1><p>Бестактный батя, свидания с подвохом и сообщения, которые лучше бы не отправлять. Читай на английском и выбирай реплики героев.</p><div class="tags"><span class="tag">${stories.length} интерактивных историй</span><span class="tag">Без регистрации</span><span class="tag">С объяснениями</span></div>${button('Мне есть 18 · Начать','adult')}<small>Внутри: ненормативная лексика и обсуждение интимных выражений в учебном контексте.</small></div></main>`;}
const expandedTranslations=new Set();
function render(focus=false){document.title=activeStory&&(view==='story'||view==='story-result')?`${textFor(storyById[activeStory],'title',storyLangs.translation)} — Duo34`:'Duo34 — истории без цензуры';root.querySelectorAll('[data-action="translation-toggle"]').forEach(b=>{if(b.getAttribute('aria-expanded')==='true')expandedTranslations.add(b.getAttribute('aria-controls'));else expandedTranslations.delete(b.getAttribute('aria-controls'));});root.querySelectorAll('[data-translation-id]').forEach(d=>{if(d.open)expandedTranslations.add(d.dataset.translationId);else expandedTranslations.delete(d.dataset.translationId);});root.innerHTML=(storageWorks?'':'<div class="storage-warning" role="alert">Браузер не разрешает сохранять данные. Прогресс доступен до закрытия страницы.</div>')+(!state.adult?intro():view==='story'?storyScreen(state,activeStory,storyLangs):view==='story-result'?storyFinish(storyResult,storyLangs):view==='stories'?shell(roadmap(state,storyLangs),storyLangs.ui):view==='lesson'?lesson():view==='result'?finish():view==='words'?dictionary():view==='review'?review():view==='progress'?progress():course());root.querySelectorAll('[data-action="translation-toggle"]').forEach(b=>{const id=b.getAttribute('aria-controls');if(expandedTranslations.has(id)){b.setAttribute('aria-expanded','true');document.getElementById(id).hidden=false;}});root.querySelectorAll('[data-translation-id]').forEach(d=>d.open=expandedTranslations.has(d.dataset.translationId));if(view==='story'&&state.adult&&supportsStoryAudio(storyById[activeStory],storyLangs.study))storyAudio.show(currentClip(storyById[activeStory],state.storyProgress[activeStory],audioManifest,undefined,storyLangs.study));else storyAudio.leave();updateAudioControls();if(focus){window.scrollTo(0,0);root.querySelector('h1')?.focus({preventScroll:true});}}
root.addEventListener('input',e=>{if(e.target.id==='search')document.querySelector('#word-list').innerHTML=wordCards(e.target.value);});
root.addEventListener('click',e=>{const b=e.target.closest('button[data-action],a[data-action]');if(!b||b.disabled)return;if(b.tagName==='A'){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button!==0)return;e.preventDefault();}const a=b.dataset.action;
if(a==='translation-toggle'){const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));document.getElementById(b.getAttribute('aria-controls')).hidden=!open;return;}
if(a.startsWith('story-')){
 if(a==='story-lang-study'){storyLangs=normalizeStoryLangs({...storyLangs,study:b.dataset.lang});saveStoryLangs();router.navigate(activeStory?storyHref(activeStory,routeStoryLangs(storyLangs)):viewHref(view,routeStoryLangs(storyLangs)));return;}
 if(a==='story-lang-translation'){storyLangs=normalizeStoryLangs({...storyLangs,translation:b.dataset.lang});saveStoryLangs();router.navigate(activeStory?storyHref(activeStory,routeStoryLangs(storyLangs)):viewHref(view,routeStoryLangs(storyLangs)));return;}
 if(a==='story-lang-ui'){storyLangs=normalizeStoryLangs({...storyLangs,ui:b.dataset.lang});saveStoryLangs();render();return;}
 if(a==='story-lang-pedagogy'){storyLangs=normalizeStoryLangs({...storyLangs,pedagogy:b.dataset.lang});saveStoryLangs();render();return;}
 if(a==='story-sound'){storyAudio.toggle();return;}
 if(a==='story-line-audio'){storyAudio.replay(revealedClip(storyById[activeStory],state.storyProgress[activeStory],audioManifest,Number(b.dataset.index),storyLangs.study));return;}
 if(a==='story-open'){router.navigate(storyHref(b.dataset.id,routeStoryLangs(storyLangs)));return;}
 if(a==='story-exit'){router.navigate(viewHref('stories',routeStoryLangs(storyLangs)));return;}
 if(a==='story-answer'){answerStory(state,activeStory,Number(b.dataset.option));save();render();document.querySelector('[data-action="story-next"]')?.focus({preventScroll:true});document.querySelector('.story-answer-note')?.scrollIntoView({block:'end'});return;}
 if(a==='story-next'){storyResult=advanceStory(state,activeStory);save();if(storyResult){analytics.finish('story',activeStory,storyResult.score);view='story-result';render(true);}else{render();document.querySelector('#story-cursor')?.scrollIntoView({block:'end'});}return;}
}
if(a==='nav'||a==='course'||a==='leave'||a==='review'){router.navigate(viewHref(a==='nav'?b.dataset.view:a==='review'?'review':'course',routeStoryLangs(storyLangs)));return;}
switch(a){case'adult':state.adult=true;save();router.refresh();return;case'nav':view=b.dataset.view;break;case'course':case'leave':view='course';exitPrompt=false;break;case'exit':exitPrompt=true;break;case'stay':exitPrompt=false;break;case'resume':if(state.session?.mode==='lesson')analytics.begin('lesson',state.session.lessonId,true);view='lesson';selected=state.session?.selected??null;exitPrompt=false;break;case'start':if(state.session&&state.session.lessonId!==b.dataset.id){view='course';render(true);const resume=root.querySelector('.resume');if(resume){resume.insertAdjacentHTML('beforeend','<p class="meta">Сначала заверши начатое занятие. Его прогресс уже сохранён.</p>');resume.scrollIntoView({block:'center'});}return;}const resumedLesson=!!state.session;if(!state.session)start(state,b.dataset.id);if(state.session?.mode==='lesson')analytics.begin('lesson',state.session.lessonId,resumedLesson);view='lesson';selected=null;save();break;case'review':view='review';break;case'start-review':if(state.session){view='course';render(true);root.querySelector('.resume')?.scrollIntoView({block:'center'});return;}if(start(state,null,true)){view='lesson';selected=null;save();}break;case'choose':selected=orderedChoices(current(state))[Number(b.dataset.choice)];render();root.querySelector(`button[data-choice="${b.dataset.choice}"]`)?.focus({preventScroll:true});return;case'check':if(selected!==null){answer(state,selected);save();}render();root.querySelector('[data-action="next"]')?.focus({preventScroll:true});return;case'next':result=advance(state);selected=null;save();if(result){if(result.mode==='lesson')analytics.finish('lesson',result.lessonId,result.score);view='result';}break;}render(!['exit','stay'].includes(a));});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea')||e.ctrlKey||e.metaKey||e.altKey)return;if(view==='story'&&state.adult){if(['1','2','3'].includes(e.key)){e.preventDefault();root.querySelector(`[data-option="${Number(e.key)-1}"]`)?.click();}else if(e.key==='Enter'&&e.target.tagName!=='BUTTON'&&e.target.tagName!=='SUMMARY'&&e.target.tagName!=='A'){e.preventDefault();root.querySelector('[data-action="story-next"]')?.click();}return;}if(view==='lesson'&&!exitPrompt&&state.adult){if(['1','2','3'].includes(e.key)&&!state.session?.answered){e.preventDefault();root.querySelector(`[data-choice="${Number(e.key)-1}"]`)?.click();}else if(e.key==='Enter'&&e.target.tagName!=='BUTTON'&&e.target.tagName!=='SUMMARY'&&e.target.tagName!=='A'){e.preventDefault();root.querySelector(`[data-action="${state.session?.answered?'next':'check'}"]`)?.click();}}});
const router=createHashRouter({window,stories:storyById,getDefaultPair:()=>routeStoryLangs(storyLangs),onRoute(route){
 storyAudio.leave();exitPrompt=false;selected=null;storyResult=null;
 if(route.explicitPair){storyLangs=normalizeStoryLangs({...storyLangs,study:route.langs.source,translation:route.langs.target});saveStoryLangs();}
 view=route.view;activeStory=route.view==='story'?route.id:null;
 if(activeStory&&state.adult){
  const resumed=!!state.storyProgress[activeStory];
  beginStory(state,activeStory);analytics.begin('story',activeStory,resumed);save();
 }
 render(true);
 if(activeStory&&state.adult)setTimeout(()=>document.querySelector('#story-cursor')?.scrollIntoView({block:'center'}),0);
}});
router.start();
