import {lessons,allQuestions,questions} from './course.js';
export const KEY='duo34-v1';
const byId=new Map(allQuestions.map(q=>[q.id,q]));
export const dayKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export function initial(){return {version:1,adult:false,xp:0,completed:{},mistakes:[],days:[],session:null};}
export function restore(raw){try {const p=JSON.parse(raw); if(p?.version!==1) return initial(); const s=initial();s.adult=p.adult===true;s.xp=Number.isFinite(p.xp)&&p.xp>=0?p.xp:0;s.completed=Object.fromEntries(Object.entries(p.completed||{}).filter(([id,n])=>lessons.some(l=>l.id===id)&&Number.isInteger(n)&&n>=0&&n<=8));s.mistakes=[...new Set((Array.isArray(p.mistakes)?p.mistakes:[]).filter(id=>byId.has(id)))];s.days=[...new Set((Array.isArray(p.days)?p.days:[]).filter(d=>/^\d{4}-\d{2}-\d{2}$/.test(d)))];const t=p.session;if(t&&Array.isArray(t.ids)&&t.ids.length>0&&t.ids.every(id=>byId.has(id))&&Number.isInteger(t.index)&&t.index>=0&&t.index<t.ids.length&&Number.isInteger(t.score)&&t.score>=0&&t.score<=t.index+(t.answered?1:0)&&(t.mode==='review'||lessons.some(l=>l.id===t.lessonId))){s.session={...t};if(t.answered&&!byId.get(t.ids[t.index]).choices.includes(t.selected)){s.session=null;}}return s;}catch{return initial();}}
export function start(s,lessonId,review=false){const ids=review?s.mistakes.slice():questions[lessonId]?.map(q=>q.id);if(!ids?.length)return false;s.session={lessonId:review?'review':lessonId,mode:review?'review':'lesson',ids,index:0,score:0,answered:false,selected:null};return true;}
export function current(s){return s.session?byId.get(s.session.ids[s.session.index]):null;}
export function answer(s,value){const t=s.session,q=current(s);if(!t||t.answered||!q.choices.includes(value))return null;const correct=value===q.correct;t.answered=true;t.selected=value;if(correct){t.score++;s.mistakes=s.mistakes.filter(id=>id!==q.id);}else if(!s.mistakes.includes(q.id))s.mistakes.push(q.id);return correct;}
export function advance(s,date=new Date()){const t=s.session;if(!t?.answered)return null;if(t.index<t.ids.length-1){t.index++;t.answered=false;t.selected=null;return null;}const isNew=t.mode==='lesson'&&s.completed[t.lessonId]===undefined;const gained=t.score*5+(isNew?10:0);s.xp+=gained;if(t.mode==='lesson')s.completed[t.lessonId]=Math.max(s.completed[t.lessonId]??0,t.score);const day=dayKey(date);if(!s.days.includes(day))s.days.push(day);const result={score:t.score,total:t.ids.length,xp:gained,lessonId:t.lessonId,mode:t.mode};s.session=null;return result;}
export function streak(s,date=new Date()){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate(),12);if(!s.days.includes(dayKey(d)))d.setDate(d.getDate()-1);let count=0;while(s.days.includes(dayKey(d))){count++;d.setDate(d.getDate()-1);}return count;}
export function orderedChoices(q){const n=[...q.id].reduce((a,c)=>a+c.charCodeAt(0),0)%3;return q.choices.slice(n).concat(q.choices.slice(0,n));}
