// Original adult comedy scenes. All characters are adults; dialogue is linguistic, not erotic.
const say=(who,en,ru)=>({type:'line',who,en,ru});
const scene=(ru)=>({type:'scene',ru});
const choice=(who,prompt,options,correct,ru,note)=>({type:'choice',who,prompt,options,correct,ru,note});
export const cast={
 dad:{name:'Батя',age:52,color:'#b7ee65',shape:'square'},son:{name:'Лёша',age:23,color:'#9cd7ff',shape:'round'},
 roxy:{name:'Рокси',age:29,color:'#ffadbc',shape:'round'},zoya:{name:'Зоя',age:31,color:'#c7b6ff',shape:'square'},
 chad:{name:'Чедрик',age:27,color:'#b7ee65',shape:'square'},krinzh:{name:'Кринжина',age:26,color:'#ffbb8a',shape:'round'},
 max:{name:'Макс',age:28,color:'#a9cff4',shape:'square'}
};
export const stories=[
 {id:'dad',title:'Батя, выражайся точнее',enTitle:'The Family Dictionary',subtitle:'Один сын. Один батя. Слишком много синонимов.',place:'Кухня, 11:43',color:'#b7ee65',cast:['dad','son'],prop:'☕',topic:'Анатомия, сленг и буквальный смысл',ending:'Батя хотел подробностей. Получил лингвистическую экспертизу.',nodes:[
 scene('Субботнее утро. Лёша, 23 года, вернулся от своей девушки Ани, 24. Батя, 52, уже поставил чайник и приготовил бестактный вопрос.'),
 say('dad','So. Did you sleep with Anna?','Ну что. Ты с Аней спал?'),
 say('son','Yeah. Eight hours. Fantastic mattress.','Да. Восемь часов. Охрененный матрас.'),
 say('dad','Don’t be a smartass. Did you get laid?','Не умничай. Потрахался-то?'),
 choice('son','Лёша продолжает делать вид, что речь о сне. Выбери его реплику.',["Yes, Dad. Horizontally. On the mattress.","Yes, Dad. I laid the kitchen tiles.","No, Dad. She made excellent tea."],0,'Да, батя. Горизонтально. На матрасе.','Get laid — грубовато-разговорное «заняться сексом». Лёша намеренно цепляется за буквальное «уложить».'),
 say('dad','Your dick. Her pussy. Am I being clear enough?','Твой хуй. Её пизда. Теперь достаточно понятно?'),
 say('son','Anna doesn’t have a cat.','У Ани нет кошки.'),
 say('dad','Not a cat. Pussy. Twat. Cunt. The downstairs department!','Не кошка. Киска. Манда. Пизда. Отдел на нижнем этаже!'),
 choice('son','Сын подхватывает последнюю метафору, будто обсуждает недвижимость.',["I’m buying cat food.","Dad, she lives on the ground floor.","Thanks for the anatomy lesson."],1,'Батя, она живёт на первом этаже.','Downstairs буквально «внизу», а здесь — эвфемизм для гениталий. Сын снова притворяется, что понимает буквально.'),
 say('dad','Fine. Her vagina. There. A proper word.','Ладно. Её влагалище. Вот. Нормальное слово.'),
 say('son','If you mean the outside, that’s the vulva.','Если ты про наружную часть — это вульва.'),
 say('dad','I’m trying to have a father-son talk, not pass a fucking medical exam.','Я пытаюсь поговорить с сыном, а не сдать ебучий экзамен по анатомии.'),
 choice('son','Лёша заканчивает свою лекцию. Какая реплика анатомически точна?',["Vulva outside, vagina inside. Your turn, Professor.","Vagina outside, vulva inside. Your turn, Professor.","Vulva and vagina mean exactly the same thing."],0,'Вульва снаружи, влагалище внутри. Теперь ты, профессор.','Vulva — наружные женские половые органы; vagina — внутренний канал. Грубые слова не обладают такой анатомической точностью.'),
 say('dad','When I was your age, we just called it a fanny.','В твоём возрасте мы просто называли это fanny.'),
 say('son','In Britain, maybe. In America, that’s a butt.','В Британии — возможно. В Америке это задница.'),
 say('dad','So the same word changes body parts at passport control?','То есть слово меняет часть тела на паспортном контроле?'),
 choice('son','Лёша ставит точку: это языковой разбор, а не отчёт о свидании.',["Anyway, here’s Anna’s phone number.","Anyway, my sex life is none of your business.","Anyway, you should call her mother."],1,'Короче, моя сексуальная жизнь — не твоё дело.','None of your business — резкое «не твоё дело». Pussy многозначно; twat и особенно cunt — грубые слова и оскорбления, а не нейтральные названия.'),
 say('dad','Fine. How was the tea?','Ладно. Как чай?'),
 say('son','Hot. But don’t get excited.','Горячий. Только не возбуждайся.'),
 scene('Чайник свистит. Впервые за всё утро — кто-то по делу.')
 ]},
 {id:'change-mind',title:'Можно передумать',enTitle:'The Exit Clause',subtitle:'Свидание — не ипотечный договор.',place:'Бар, 22:16',color:'#ffadbc',cast:['roxy','zoya'],prop:'🍷',topic:'Отказ, намерения и change your mind',ending:'Рокси не осталась из вежливости. Зоя осталась ради картошки.',nodes:[
 scene('Рокси, 29, пришла в бар после свидания с Максом, 28. Зоя, 31, заказала картошку и готова к разбору полётов.'),
 say('roxy','He was nice. I went back to his place. Then I changed my mind.','Он был милый. Я поехала к нему. А потом передумала.'),
 say('zoya','And?','И?'),
 say('roxy','Can I just leave? Even then?','Можно просто уйти? Даже в этот момент?'),
 choice('zoya','Зоя отвечает прямо. Продолжи её мысль.',["No. A date is a binding contract.","Yes. You can change your mind at any point.","Only if he agrees with your reason."],1,'Да. Ты можешь передумать в любой момент.','Change your mind — «передумать». At any point — «в любой момент», не только в начале встречи.'),
 say('zoya','If his dick is crooked and you don’t want to fuck him, don’t.','Если у него кривой хуй и ты не хочешь с ним ебаться — не ебись.'),
 say('roxy','What if his dick is perfectly straight?','А если у него идеально прямой хуй?'),
 say('zoya','Still not a fucking obligation. You’re not a building inspector.','Это всё ещё не ебучая обязанность. Ты не строительный инспектор.'),
 choice('roxy','Рокси проверяет, правильно ли поняла: причина вообще обязательна?',["So I need a doctor’s note?", "So I don’t need an excuse?", "So I need to inspect him first?"],1,'То есть мне не нужно оправдание?','Excuse здесь — «оправдание / отговорка», а не извинение. Рокси не обязана доказывать, что причина достаточно веская.'),
 say('zoya','Exactly. Maybe you’re tired. Maybe the mood’s gone. Maybe his pillow says “ALPHA”.','Именно. Может, ты устала. Может, настроение прошло. Может, у него на подушке написано «АЛЬФА».'),
 say('roxy','His pillow DID say ALPHA.','У него на подушке И БЫЛО написано «АЛЬФА».'),
 say('zoya','Jesus. Even the bedding is a red flag.','Господи. Даже постельное бельё — красный флаг.'),
 choice('roxy','Выбери короткую реплику, которой Рокси может закончить встречу.',["I’m not in the mood anymore. I’m going home.","I guess I owe you now.","You paid, so it’s your decision."],0,'Я больше не в настроении. Я еду домой.','Anymore — «больше не». Реплика сообщает решение; она не просит разрешения отказаться.'),
 say('roxy','He said, “But I bought dinner.”','Он сказал: «Но я же оплатил ужин».'),
 say('zoya','Congratulations to him. He understands how restaurants work.','Поздравляю его. Он понимает, как работают рестораны.'),
 choice('zoya','Зоя добивает аргумент про ужин. Какая реплика подходит?',["Dinner is a deposit.","You owe him another chance.","Dinner isn’t a down payment on sex."],2,'Ужин — не первоначальный взнос за секс.','Down payment — первоначальный взнос. Здесь это саркастическая финансовая метафора, а не описание договорённости.'),
 say('roxy','I left. He called me a bitch.','Я ушла. Он назвал меня сукой.'),
 say('zoya','And you called a taxi. Excellent division of labour.','А ты вызвала такси. Отличное разделение труда.'),
 scene('Зоя подвигает картошку. У картошки нет условий мелким шрифтом.')
 ]},
 {id:'compliment',title:'Это комплимент, идиот',enTitle:'One Tiny Word',subtitle:'Чедрик экономит на артиклях. Зря.',place:'Квартира Рокси, 19:05',color:'#b7d9ff',cast:['chad','roxy'],prop:'♫',topic:'Shit / the shit, insult / compliment',ending:'Чедрик выучил артикль. Рокси сохранила достоинство и пароль от Wi-Fi.',nodes:[
 scene('Чедрик, 27, пришёл в гости к Рокси, 29. Она включает свой новый диджейский сет. Он решил звучать как носитель.'),
 say('chad','Your playlist is shit.','Твой плейлист — говно.'),
 say('roxy','Sorry. My playlist is WHAT?','Прости. Мой плейлист — ЧТО?'),
 say('chad','Shit! Like, really good shit!','Говно! Ну, типа, очень хорошее говно!'),
 choice('chad','Чедрик хотел сказать «это охуенно». Спаси комплимент одним артиклем.',["Your playlist is the shit!", "Your playlist is a shit!", "Your playlist is more shit!"],0,'Твой плейлист — это охуенно!','The shit — грубая сленговая похвала. Is shit без the — обычно отрицательная оценка.'),
 say('roxy','One tiny word. Huge fucking difference.','Одно крошечное слово. Охуенно большая разница.'),
 say('chad','Okay. You’re a bitch.','Ладно. Ты сука.'),
 say('roxy','Do you have a death wish or a broken dictionary?','Ты смерти ищешь или у тебя словарь сломан?'),
 choice('chad','Он пытается извиниться, а не объяснить Рокси, что она обиделась неправильно.',["You’re too sensitive.","I meant it as a compliment. That came out wrong. Sorry.","It’s your fault for listening."],1,'Я хотел сделать комплимент. Неудачно выразился. Прости.','That came out wrong — «неудачно прозвучало / я не так выразился». Намерение и эффект реплики могут различаться.'),
 say('chad','A rapper called herself a bad bitch. She seemed happy.','Рэперша назвала себя bad bitch. Она вроде была довольна.'),
 say('roxy','She called HERSELF that. You called your hostess a bitch.','Она СЕБЯ так назвала. А ты назвал хозяйку дома сукой.'),
 say('chad','Context. My natural enemy.','Контекст. Мой природный враг.'),
 choice('roxy','Рокси предлагает комплимент без лингвистического самоубийства.',["Try: ‘You’re an asshole.’", "Try: ‘You have terrible taste.’", "Try: ‘You’ve got amazing taste in music.’"],2,'Попробуй: «У тебя потрясающий музыкальный вкус».','Taste in music — музыкальный вкус. Самоназвание из песни не становится универсальным обращением к другому человеку.'),
 say('chad','You’ve got amazing taste in music.','У тебя потрясающий музыкальный вкус.'),
 say('roxy','Thank you. See? No casualties.','Спасибо. Видишь? Обошлось без жертв.'),
 choice('chad','Чедрик спрашивает про ещё один сленговый комплимент.',["So ‘you killed it’ can mean ‘you did brilliantly’?", "So ‘you killed it’ always means murder?", "So ‘you killed it’ means ‘you’re a bitch’?"],0,'То есть you killed it может значить «ты шикарно справилась»?','You killed it в контексте выступления — не буквальное убийство, а восторженная похвала.'),
 say('roxy','Yes. And “please leave” means please leave.','Да. А please leave означает «пожалуйста, уходи».'),
 say('chad','Finally. An expression I can’t fuck up.','Наконец-то. Выражение, с которым я не накосячу.'),
 scene('Он толкает дверь с надписью PULL.')
 ]},
 {id:'netflix',title:'Netflix — это Netflix',enTitle:'Absolutely No Chill',subtitle:'Он подготовил намёк. Она — блокнот.',place:'Диван, 21:00',color:'#c7b6ff',cast:['max','krinzh'],prop:'▣',topic:'Намёки, literally, be into something',ending:'Романтика ушла в канализацию. Документалка оказалась отличной.',nodes:[
 scene('Макс, 28, пригласил Кринжину, 26, на Netflix and chill. Она принесла блокнот с надписью «ГОРОДСКАЯ ИНФРАСТРУКТУРА».'),
 say('max','So… Netflix and chill?','Ну что… Netflix and chill?'),
 say('krinzh','Absolutely. I found a documentary about sewers.','Конечно. Я нашла документалку про канализацию.'),
 say('max','That’s not quite what I had in mind.','Я немного другое имел в виду.'),
 choice('krinzh','Кринжина пока не распознала намёк и уточняет выбор фильма.',["You mean… a documentary about septic tanks?", "Yes, let’s ignore what I want.", "I already know exactly what you mean."],0,'Ты имеешь в виду… документалку про септики?','Have in mind — «иметь в виду / задумать». Она воспринимает приглашение буквально, а не как сексуальный намёк.'),
 say('max','I was trying to make a move.','Я пытался подкатить.'),
 say('krinzh','There’s room on the other side of the sofa.','На другом конце дивана есть место.'),
 say('max','Not a furniture move. A romantic move.','Не мебельный манёвр. Романтический.'),
 choice('krinzh','Она наконец понимает намёк, но говорит, чего хочет сама.',["Oh. Then I have no choice.", "Oh. I’m only here for the film.", "Oh. My notebook means yes."],1,'А. Я здесь только ради фильма.','Make a move — проявить романтическую инициативу. Only here for the film ясно ограничивает смысл согласия на встречу.'),
 say('max','Fair enough. No pressure.','Ладно, понимаю. Без давления.'),
 say('krinzh','Good. The sewers have enough pressure already.','Отлично. В канализации и так давления хватает.'),
 say('max','Are you seriously into this shit?','Тебя серьёзно увлекает это дерьмо?'),
 choice('krinzh','Документалка про сточные воды. Продолжи буквальную шутку.',["No, ‘shit’ is always a compliment.", "Yes. Literally. That’s what the film is about.", "No, ‘into’ means I live inside a sewer."],1,'Да. Буквально. Фильм именно об этом.','Be into something — увлекаться чем-то. This shit бывает грубым «эта фигня», но здесь дерьмо ещё и буквальная тема фильма.'),
 say('max','I even changed the bedsheets.','Я даже постельное бельё поменял.'),
 say('krinzh','Good for you. Hygiene isn’t foreplay.','Молодец. Гигиена — не прелюдия.'),
 choice('max','Макс принимает её ответ и возвращается к фильму.',["Fine. Pass the popcorn. What’s a fatberg?", "Clean sheets mean you owe me.", "I’ll keep asking until you say yes."],0,'Ладно. Передай попкорн. Что такое fatberg?','Pass the popcorn — передай попкорн. Fatberg — затвердевшая масса жира и отходов в канализации. Вот уж неожиданный словарь свидания.'),
 say('krinzh','Finally, a man asking the right questions.','Наконец-то мужчина задаёт правильные вопросы.'),
 say('max','This date went down the drain.','Это свидание пошло коту под хвост.'),
 scene('На экране показывают трубу. Кринжина просит перемотать назад. Макс впервые за вечер действительно заинтригован.')
 ]},
 {id:'translator',title:'Слишком честный переводчик',enTitle:'Send All',subtitle:'Пять черновиков. Одна кнопка. Пиздец.',place:'Переписка, 00:14',color:'#ffbb8a',cast:['krinzh','zoya'],prop:'✉',topic:'Черновики, get lost, send / delete',ending:'Сообщение получилось предельно ясным. Особенно последнее.',nodes:[
 scene('Кринжина, 26, хочет отказать настойчивому знакомому, 30. Зоя, 31, помогает сделать английское сообщение менее взрывоопасным.'),
 say('krinzh','Draft one: “Fuck off, you self-obsessed prick.”','Черновик первый: «Отъебись, самовлюблённый мудак».'),
 say('zoya','Clear. Concise. Possibly not the tone you asked for.','Ясно. Кратко. Возможно, не совсем тот тон, который ты просила.'),
 say('krinzh','I asked the translator to make it warmer.','Я попросила переводчик сделать потеплее.'),
 choice('zoya','Зоя подозревает, что переводчик добавил вежливость только снаружи.',["Did it say ‘Fuck off, please’?", "Did it delete your phone?", "Did it order a radiator?"],0,'Он написал «Отъебись, пожалуйста»?','Please не обезвреживает fuck off. Формальная вежливость и грубость могут комически уживаться в одной реплике.'),
 say('krinzh','“Dear self-obsessed prick, kindly fuck off.”','«Дорогой самовлюблённый мудак, будьте любезны отъебаться».'),
 say('zoya','Ah. Corporate hostility.','А. Корпоративная враждебность.'),
 choice('krinzh','Кринжина пробует обозначить границу без оскорбления.',["I’m not interested. Please stop messaging me.", "Please continue, you prick.", "You’re kindly a fucking idiot."],0,'Я не заинтересована. Пожалуйста, перестань мне писать.','Not interested — не заинтересована. Stop messaging me — перестань писать мне сообщения. Просьба конкретна и не обещает «может быть потом».'),
 say('zoya','That one. Send that one. Delete the others.','Вот это. Отправь вот это. Остальные удали.'),
 say('krinzh','There’s a button that says “Send all”.','Тут кнопка «Отправить всё».'),
 choice('zoya','Зоя пытается успеть раньше пальца Кринжины.',["Yes. All means only the last one.", "No! Send only the last draft!", "Great. He needs the whole collection."],1,'Нет! Отправь только последний черновик!','Send all — отправить всё. Only the last draft — только последний черновик. Здесь от only зависит масштаб катастрофы.'),
 scene('Кринжина смотрит на пять синих галочек.'),
 say('krinzh','Too late. He’s reading my entire character development.','Поздно. Он читает всю эволюцию моей личности.'),
 say('zoya','From “prick” to “please”. A moving journey.','От «мудака» до «пожалуйста». Трогательный путь.'),
 say('krinzh','He replied: “So… is that a maybe?”','Он ответил: «То есть… это может быть?»'),
 choice('krinzh','Нужно убрать последнюю двусмысленность. Выбери ответ.',["Perhaps you should guess again.", "Maybe means absolutely yes.", "No. It’s a no. Don’t contact me again."],2,'Нет. Это нет. Больше со мной не связывайся.','It’s a no — недвусмысленное «ответ — нет». Don’t contact me again относится ко всем способам связи, не только этому чату.'),
 say('zoya','No translation needed.','Перевод не требуется.'),
 say('krinzh','For once, my English isn’t the fucking problem.','Хоть раз проблема, блядь, не в моём английском.'),
 scene('Она блокирует контакт. Переводчик предлагает: «Сделать текст дружелюбнее?»')
 ]}
];
export const storyById=Object.fromEntries(stories.map(s=>[s.id,s]));
