import {promptMarkup,choiceCard} from './choice-ui.js';
import {stories,storyById,cast} from './stories.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const speakerIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4Z"/><path d="M15 8a6 6 0 0 1 0 8M18 5a10 10 0 0 1 0 14"/></svg>';
export const stopIcon='<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="2"/></svg>';
function lineButton(s,index){return `<button class="line-audio" data-action="story-line-audio" data-index="${index}" data-clip-key="${s.id}:${index}" aria-label="Прослушать реплику" title="Прослушать реплику">${speakerIcon}</button>`;}
export const bookIcon='<svg viewBox="0 0 40 36" fill="none" aria-hidden="true"><path d="M20 8Q12 2 3 5v24q9-3 17 3 8-6 17-3V5Q28 2 20 8Z" fill="currentColor"/><path d="M20 9v21M8 12l7 2M8 18l7 2M25 14l7-2M25 20l7-2" stroke="#20242c" stroke-width="2.2" stroke-linecap="round"/></svg>';
export function face(id){const c=cast[id];return `<svg class="cast-face" viewBox="0 0 80 88" role="img" aria-label="${c.name}"><rect x="7" y="8" width="66" height="74" rx="${c.shape==='square'?17:32}" fill="${c.color}"/>${id==='dad'?'<path d="M24 12L42 3L61 13" fill="#536235"/><path d="M25 59h30l-7 7h-7l-5-4-5 4Z" fill="#344329"/>':id==='zoya'?'<path d="M7 45V24Q7 0 39 5Q75 0 73 31L55 18L25 25Z" fill="#654b94"/>':id==='roxy'?'<path d="M7 30Q2 3 42 4Q71 1 75 32L44 17L35 29Z" fill="#923d60"/>':id==='krinzh'?'<path d="M7 33L11 9L33 6L48 13L69 8L76 38L54 23L37 31L23 22Z" fill="#995b3b"/>':id==='chad'?'<path d="M7 32L8 8L33 3L60 5L71 20L30 16Z" fill="#536235"/>':''}<g fill="#20242c"><rect x="23" y="38" width="8" height="12" rx="4"/><rect x="49" y="38" width="8" height="12" rx="4"/></g><path d="M32 62q8 7 16 0" stroke="#20242c" stroke-width="3.5" fill="none" stroke-linecap="round"/></svg>`;}
function cover(s){return `<span class="cover-scene"><span class="cover-face left">${face(s.cast[0])}</span><span class="cover-prop" aria-hidden="true">${s.prop}</span><span class="cover-face right">${face(s.cast[1])}</span><span class="cover-book">${bookIcon}</span></span>`;}
export function roadmap(state){const count=Object.keys(state.storyCompleted||{}).length;return `<section class="story-road"><div class="season-title"><span class="eyebrow">СЕЗОН 1 · ВСЕ ПЕРСОНАЖИ 18+</span><h1 tabindex="-1">Ну всё. Приехали.</h1><p>Пять историй, которые не расскажут в учебнике.</p><span class="season-count">${count} / ${stories.length} прочитано</span></div><div class="story-path">${stories.map((s,i)=>{const p=state.storyProgress?.[s.id],done=state.storyCompleted?.[s.id]!==undefined;return `<div class="story-stop" style="--cover:${s.color};--step-offset:${[0,65,20,-65,0][i]}px"><button class="story-cover ${done?'finished':''}" data-action="story-open" data-id="${s.id}" aria-label="${p?'Продолжить':done?'Перечитать':'Читать'}: ${s.title}">${cover(s)}<span class="cover-status">${p?'▶':done?'✓':String(i+1).padStart(2,'0')}</span></button><h2>${s.title}</h2><p>${p?`Продолжить · ${Math.round(p.index/s.nodes.length*100)}%`:done?'Прочитано · можно ещё раз':s.subtitle}</p><span class="story-duration">~5 минут · ${s.nodes.filter(n=>n.type==='choice').length} выбора</span></div>`;}).join('')}</div><div class="season-end">✦<p>Конец первого сезона.<br>Героям явно есть что обсудить дальше.</p></div></section>`;}
function dialogue(s,n,index,en=n.en,ru=n.ru){const c=cast[n.who],right=n.who===s.cast[1];return `<article class="dialogue ${right?'right':''}"><span class="dialogue-face">${face(n.who)}</span><div class="dialogue-content"><span class="speaker" style="color:${c.color}">${c.name}</span><div class="bubble"><div class="spoken-line"><p lang="en">${esc(en)}</p>${lineButton(s,index)}</div><details class="translation"><summary>Перевод</summary><p>${esc(ru)}</p></details></div></div></article>`;}
function bilingualText(en,ru){return `<p lang="en">${esc(en)}</p><details class="translation"><summary>Перевод</summary><p lang="ru">${esc(ru)}</p></details>`;}
function sceneNote(n){return n.en?`<div class="scene-note bilingual-note">${bilingualText(n.en,n.ru)}</div>`:`<p class="scene-note" lang="ru">${esc(n.ru)}</p>`;}
export function storyScreen(state,id){const s=storyById[id],p=state.storyProgress[id],n=s.nodes[p.index],answered=p.answers[p.index]!==undefined,correct=answered&&p.answers[p.index]===n.correct;return `<main class="story-reader"><header class="reader-head"><button class="close" data-action="story-exit" aria-label="К историям, сохранить место">×</button><div><b>${s.title}</b><div class="meter" role="progressbar" aria-label="Прогресс истории" aria-valuenow="${p.index+1}" aria-valuemin="0" aria-valuemax="${s.nodes.length}"><i style="width:${(p.index+1)/s.nodes.length*100}%;background:${s.color}"></i></div></div><span class="meta">${p.index+1}/${s.nodes.length}</span><section class="audio-controls" aria-label="Озвучка"><div><button class="audio-button" data-action="story-sound" aria-pressed="true">Автоозвучка включена</button></div><small>Голоса созданы ИИ · английские реплики</small><p id="audio-status" role="status" aria-live="polite"></p></section></header><section class="transcript" aria-label="Диалог"><div class="scene-heading"><span class="eyebrow">${s.place}</span><h1>${s.enTitle}</h1><p>${s.cast.map(c=>`${cast[c].name}, ${cast[c].age}`).join(' · ')}</p></div>${s.nodes.slice(0,p.index+1).map((x,i)=>x.type==='scene'?sceneNote(x):x.type==='line'?dialogue(s,x,i):i<p.index?dialogue(s,x,i,x.options[x.correct]):'').join('')}<div id="story-cursor">${n.type==='choice'?`<section class="story-choice"><span class="choice-label">ТВОЯ РЕПЛИКА · ${cast[n.who].name.toUpperCase()}</span>${promptMarkup(n.prompt,n.promptRu,`prompt-${s.id}-${p.index}`)}<div class="answers" role="group" aria-label="Продолжение диалога">${n.options.map((o,i)=>choiceCard({id:`option-${s.id}-${p.index}-${i}`,en:o,ru:n.optionsRu[i],index:i,action:'story-answer',attribute:'option',value:i,answered,selected:answered&&p.answers[p.index]===i,good:answered&&i===n.correct,bad:answered&&p.answers[p.index]===i&&!correct})).join('')}</div>${answered?`<div class="story-answer-note ${correct?'good':'bad'}" role="status"><b>${correct?'Да. Сцена продолжается.':'Не совсем. Вот как продолжается сцена:'}</b>${dialogue(s,n,p.index,n.options[n.correct])}<p>${esc(n.note)}</p></div>`:''}</section>`:''}</div></section><footer class="reader-footer"><span class="meta">${n.type==='choice'&&!answered?'Выбери реплику выше':'Нажми «Перевод», если слово незнакомо'}</span><button class="btn" data-action="story-next" ${n.type==='choice'&&!answered?'disabled':''}>${p.index===s.nodes.length-1?'Конец истории':'Продолжить'} <span aria-hidden="true">→</span></button></footer></main>`;}
export function storyFinish(r){const s=storyById[r.id],next=stories[stories.findIndex(x=>x.id===r.id)+1];return `<main class="lesson-screen"><section class="result story-finish"><div class="finish-cast">${s.cast.map(face).join('')}</div><span class="eyebrow">ЗАНАВЕС</span><h1 tabindex="-1">${s.title}</h1><div class="story-ending bilingual-note">${bilingualText(s.ending.en,s.ending.ru)}</div><div class="result-stats"><div class="card"><b>${r.score}/${r.total}</b><small>верных реплик</small></div><div class="card"><b>+${r.xp}</b><small>XP за историю</small></div><div class="card"><b>✓</b><small>история прочитана</small></div></div><div class="result-actions">${next?`<button class="btn" data-action="story-open" data-id="${next.id}">Следующая история →</button>`:''}<button class="btn secondary" data-action="story-exit">К историям</button></div><p class="meta" style="margin-top:25px">${s.topic}</p></section></main>`;}
