import {test} from 'node:test';import assert from 'node:assert/strict';
import {lessons,allQuestions,questions} from './course.js';
import {initial,start,current,answer,advance,restore,streak,orderedChoices} from './engine.js';
test('Course complete, unique IDs, every answer offered once',()=>{assert.equal(lessons.length,9);assert.equal(allQuestions.length,72);assert.equal(new Set(allQuestions.map(q=>q.id)).size,72);for(const q of allQuestions){assert.equal(q.choices.length,3);assert.equal(new Set(q.choices).size,3);assert.ok(q.choices.includes(q.correct));assert.ok(q.explanation.length>50);assert.deepEqual(new Set(orderedChoices(q)),new Set(q.choices));}});
test('All lessons complete, XP credited once on completion, best scores kept',()=>{const s=initial();for(const l of lessons){start(s,l.id);for(let i=0;i<8;i++){answer(s,current(s).correct);var r=advance(s,new Date(2026,8,5));}assert.equal(r.score,8);}assert.equal(s.xp,450);assert.equal(Object.keys(s.completed).length,9);assert.equal(s.days.length,1);assert.equal(advance(s),null);assert.equal(s.xp,450);start(s,lessons[0].id);for(let i=0;i<8;i++){const q=current(s);answer(s,q.choices.find(x=>x!==q.correct));advance(s);}assert.equal(s.completed[lessons[0].id],8);});
test('Wrong answer saved, double submit ignored, restore mid-answer, review clears mistake',()=>{let s=initial();start(s,lessons[0].id);const q=current(s);answer(s,q.choices.find(x=>x!==q.correct));assert.equal(answer(s,q.correct),null);assert.equal(s.session.score,0);s=restore(JSON.stringify(s));assert.equal(s.session.answered,true);assert.deepEqual(s.mistakes,[q.id]);for(let i=0;i<8;i++){if(!s.session.answered)answer(s,current(s).correct);advance(s);}assert.equal(s.xp,45);assert.equal(start(s,null,true),true);assert.equal(current(s).id,q.id);answer(s,q.correct);const r=advance(s);assert.equal(r.score,1);assert.deepEqual(s.mistakes,[]);assert.equal(start(s,null,true),false);});
test('Streak handles yesterday, skipped days and month boundaries',()=>{const s=initial();s.days=['2026-08-30','2026-08-31'];assert.equal(streak(s,new Date(2026,8,1)),2);assert.equal(streak(s,new Date(2026,8,2)),0);s.days.push('2026-09-01');assert.equal(streak(s,new Date(2026,8,1)),3);});
test('Corrupt storage safely resets or strips invalid fields',()=>{assert.deepEqual(restore('{bad'),initial());assert.deepEqual(restore(null),initial());const s=restore(JSON.stringify({version:1,completed:{bad:99},mistakes:['bad'],xp:-1,session:{ids:['bad']}}));assert.deepEqual(s.completed,{});assert.deepEqual(s.mistakes,[]);assert.equal(s.session,null);assert.equal(s.xp,0);});

import {stories,storyById,cast} from './stories.js';
import {beginStory,answerStory,advanceStory} from './story-engine.js';
test('Five complete adult stories, four valid dialogue choices each',()=>{assert.equal(stories.length,5);for(const s of stories){assert.ok(s.nodes.length>=18);assert.equal(s.nodes.filter(n=>n.type==='choice').length,4);for(const id of s.cast)assert.ok(cast[id].age>=18);for(const n of s.nodes){if(n.type==='line'){assert.ok(n.en&&n.ru);assert.ok(cast[n.who]);}if(n.type==='choice'){assert.equal(new Set(n.options).size,3);assert.ok(n.options[n.correct]);assert.ok(n.ru&&n.note&&n.prompt);}}}});
test('Legacy progress retained while story state migrates',()=>{const s=initial();s.xp=120;s.completed['lesson-1']=7;s.adult=true;delete s.storyCompleted;delete s.storyProgress;const r=restore(JSON.stringify(s));assert.equal(r.xp,120);assert.equal(r.completed['lesson-1'],7);assert.equal(r.adult,true);assert.deepEqual(r.storyProgress,{});assert.deepEqual(r.storyCompleted,{});});
test('Stories require choices, resume mid-answer, award once, allow replay',()=>{let s=initial();for(const story of stories){assert.ok(beginStory(s,story.id));while(s.storyProgress[story.id]){const p=s.storyProgress[story.id],n=story.nodes[p.index];if(n.type==='choice'){assert.equal(advanceStory(s,story.id),null);assert.equal(answerStory(s,story.id,n.correct),true);assert.equal(answerStory(s,story.id,n.correct),null);s=restore(JSON.stringify(s));assert.equal(s.storyProgress[story.id].answers[p.index],n.correct);}var r=advanceStory(s,story.id,new Date(2026,8,5));}assert.equal(r.score,4);assert.equal(r.xp,40);assert.equal(advanceStory(s,story.id),null);}assert.equal(s.xp,200);assert.equal(Object.keys(s.storyCompleted).length,5);assert.equal(s.days.length,1);beginStory(s,'dad');while(s.storyProgress.dad){const n=storyById.dad.nodes[s.storyProgress.dad.index];if(n.type==='choice')answerStory(s,'dad',(n.correct+1)%3);var last=advanceStory(s,'dad');}assert.equal(last.xp,0);assert.equal(s.storyCompleted.dad,4);});
test('Independent story bookmarks and malformed data are isolated',()=>{let s=initial();beginStory(s,'dad');advanceStory(s,'dad');beginStory(s,'netflix');assert.equal(s.storyProgress.dad.index,1);assert.equal(s.storyProgress.netflix.index,0);s=restore(JSON.stringify(s));assert.equal(s.storyProgress.dad.index,1);assert.equal(beginStory(s,'nonexistent'),false);s.storyProgress.dad={index:15,answers:{}};s.storyCompleted.dad=999;const r=restore(JSON.stringify(s));assert.equal(r.storyProgress.dad,undefined);assert.equal(r.storyCompleted.dad,undefined);assert.equal(r.storyProgress.netflix.index,0);});
