"""Reuse the established Piper voices on de; synthesize only missing clips.
Run from the repository root after registering the local audio and remote
/root/duo34-voice-20260906/generated write scopes. No service changes.
"""
import base64, hashlib, json, pathlib, shlex, subprocess
ROOT = pathlib.Path(__file__).resolve().parents[1]
def node(code):
    return json.loads(subprocess.check_output(['node','--input-type=module','-e',code],cwd=ROOT))
manifest = node("import m from './audio-manifest.js'; console.log(JSON.stringify(m))")
stories = node("import {stories} from './stories.js'; console.log(JSON.stringify(stories))")
manifest['config']['voices']['narrator']='p230'
audio = ROOT/'audio'
audio.mkdir(exist_ok=True)
# Restore exact existing clips from the current production deployment.
for clip in manifest['clips'].values():
    path = ROOT/clip['src']
    if path.exists():
        assert hashlib.sha256(path.read_bytes()).hexdigest() == clip['sha256'], str(path)
        continue
    remote = '/home/tolik/web/anatolt.ru/public_html/t/duo34/'+clip['src']
    data = subprocess.check_output(['ssh','de','ssh new '+shlex.quote('cat '+shlex.quote(remote))])
    assert hashlib.sha256(data).hexdigest() == clip['sha256'], remote
    path.write_bytes(data)
print('Existing audio verified.',flush=True)
jobs=[]
for story in stories:
    for index,n in enumerate(story['nodes']):
        if n['type']=='scene' and not n.get('en'): continue
        text=n['options'][n['correct']] if n['type']=='choice' else n['en']
        who='narrator' if n['type']=='scene' else n['who']; key=f"{story['id']}:{index}"
        existing=manifest['clips'].get(key)
        if existing and existing['text']==text and existing['who']==who: continue
        voice=manifest['config']['voices'][who]
        digest=hashlib.sha256(json.dumps({'text':text,'voice':voice,'config':manifest['config']},sort_keys=True).encode()).hexdigest()
        jobs.append({'key':key,'text':text,'who':who,'voice':voice,'hash':digest})
if jobs:
    request={'directory':'/root/duo34-voice-20260906','config':manifest['config'],'jobs':jobs}
    print(f'Synthesizing {len(jobs)} clips with existing Piper voices.',flush=True)
    raw=subprocess.check_output(['ssh','de','python3 /root/duo34-voice-20260906/piper-worker.py'],input=json.dumps(request).encode())
    results={r['hash']:r for r in json.loads(raw)}
    for job in jobs:
        r=results[job['hash']];data=base64.b64decode(r['data'])
        assert hashlib.sha256(data).hexdigest()==r['sha256']
        src='audio/'+job['hash']+'.mp3';path=ROOT/src
        if path.exists(): assert path.read_bytes()==data, 'Refusing to overwrite different audio'
        else: path.write_bytes(data)
        manifest['clips'][job['key']]={k:job[k] for k in ['text','who','voice']}
        manifest['clips'][job['key']].update(src=src,duration=r['duration'],sha256=r['sha256'])
    (ROOT/'audio-manifest.js').write_text('// Generated by ops/generate-story-audio.py using the established Piper configuration.\nexport default '+json.dumps(manifest,ensure_ascii=False,indent=2)+';\n')
print(f"Ready: {len(manifest['clips'])} verified clips.",flush=True)
